# tasks file for nginx-role

---
- name: Install NGINX on Debian/Ubuntu
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install NGINX on RedHat/CentOS
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable NGINX
  service:
    name: nginx
    state: started
    enabled: yes

